[book]
authors = ["Danfeng Shan", "Boxuan Hu"]
description = "Textbook for Introduction to Computer System in Xi'an Jiaotong University"
language = "en"
multilingual = false
src = "src"
title = "Introduction to Computer System"


[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/xjtu-ics"
git-repository-icon = "fa-github"
default-theme = "rust"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"